version: '3.6'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: railway_trafic_light
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  hasura:
    image: hasura/graphql-engine:v2.4.0
    container_name: hasura
    depends_on:
      - "postgres"
    restart: always
    ports:
      - "8081:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/railway_trafic_light
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup,http-log,webhook-log,websocket-log,query-log
      HASURA_GRAPHQL_ADMIN_SECRET: 123
      HASURA_GRAPHQL_AUTH_HOOK_MODE: POST
      HASURA_GRAPHQL_V1_BOOLEAN_NULL_COLLAPSE: "true"
      HASURA_SERVER_COMMON_SECRET: 1245